Repository appuio/component-cloud-portal, pull requests merged in 2022-02, with the labels that each got.

#3 Initialize Component
  class/cloud-portal.yml
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/cloud-portal/cloud-portal/00_namespace.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/configmap.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/deployment.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/service.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/serviceaccount.yaml
Labels: enhancement

#4 Upgrade to chart version `v0.3.0`
  class/defaults.yml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/configmap.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/deployment.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/service.yaml
  tests/golden/defaults/cloud-portal/cloud-portal/01_cloud_portal_helmchart/cloud-portal/templates/serviceaccount.yaml
Labels: dependency

#7 Adjust Helm chart specification to use new best practice format
  class/cloud-portal.yml
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: breaking
